### ISSUE TITLE
Compatibility with Cython >=3.0.0

### ISSUE THREAD

**Issue by g-simmons** [Roche/pyreadstat#233]
Hi there,

I noticed an installation failure attempting to install pyreadstat in a Python 3.11 environment with Cython >=3.0.0.

Keeping my notes here in case they are useful to others.

### Notes

Cython version is not specified in pyproject.toml, leading to install of >=3.0.0 by default.

https://github.com/Roche/pyreadstat/blob/03214b86bb8be8fd97910b37ff825f9d7531089a/pyproject.toml#L5

However, setup.py checks that the Cython minor version is greater than 28.

https://github.com/Roche/pyreadstat/blob/03214b86bb8be8fd97910b37ff825f9d7531089a/setup.py#L29-L32

This leads to an error message when Cython 3.0.0 is installed.

It looks like Cython may have [recently switched versioning schemes](https://github.com/cython/cython/releases).

**Potential workaround** - downgrade Cython to 0.28 or 0.29. Note that this only works with Python <3.10.

With Python 3.10+ installed, attempting to downgrade Cython leads to a different error...

```
        File "/private/var/folders/b_/8s655bvn3bqfj_qkwfxmfdwm0000gn/T/pip-install-jhfdpola/cython_5f5df06e57ae4bbb92a1f56f75893eb4/Cython/Build/Dependencies.py", line 719, in create_extension_list
          elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
                                                                            ^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'collections' has no attribute 'Iterable'
      [end of output]
```

... since collections.Iterable is no longer available in Python 3.10+ (see [here](https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python)).

**Comment by ofajardo** [comment]
Thanks for the report. Solved in the new released version 1.2.3.
